# Generated by Django 3.0.3 on 2020-09-21 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20200921_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('Fashion', 'Fashion'), ('Toys', 'Toys'), ('Electronics', 'Electronics'), ('Home', 'Home'), ('Clothes', 'Clothes'), ('Other', 'Other')], default=('Other', 'Other'), max_length=64, verbose_name='Category '),
        ),
    ]
