# Generated by Django 3.0.3 on 2020-09-23 20:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20200923_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='publishdate',
            field=models.DateField(auto_created=datetime.datetime(2020, 9, 23, 20, 4, 8, 790330, tzinfo=utc), default=datetime.datetime(2020, 9, 23, 20, 4, 8, 790330, tzinfo=utc)),
        ),
    ]
