# Generated by Django 3.0.3 on 2020-09-23 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auto_20200923_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='publishdate',
            field=models.DateField(auto_now_add=True),
        ),
    ]
