# Generated by Django 3.0.3 on 2020-09-24 15:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_sold'),
    ]

    operations = [
        migrations.AddField(
            model_name='sold',
            name='solddate',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
