# Generated by Django 3.0.3 on 2020-09-24 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_sold_solddate'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='terminated',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
