# Generated by Django 3.0.3 on 2020-09-24 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_auto_20200924_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sold',
            name='solddate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
