# Generated by Django 3.0.3 on 2020-09-25 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_watchlistm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='publishdate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
