# Generated by Django 3.0.3 on 2020-09-25 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_auto_20200925_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='terminated',
            field=models.BooleanField(auto_created=True, default=False),
        ),
    ]
